services:
  linux-prometheus:
    image: prom/prometheus:latest
    container_name: linux-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    networks:
      - linux-grafana-net

  linux-grafana:
    image: grafana/grafana:latest
    container_name: linux-grafana
    ports:
      - "13030:3000"
    networks:
      - linux-grafana-net
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=mysecurepassword
    depends_on:
      - linux-prometheus

networks:
  linux-grafana-net:
    driver: bridge
