services:
  linux-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: linux-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - linux-kafka-net

  linux-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: linux-kafka
    depends_on:
      - linux-zookeeper
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: linux-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://linux-kafka:29092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - linux-kafka-net

  linux-kafka-exporter:
    image: danielqsj/kafka-exporter:latest  # Kafka exporter image
    container_name: linux-kafka-exporter
    command:
      - '--kafka.server=linux-kafka:29092'  # Connect to Kafka's internal listener
    ports:
      - "19308:9308"  # Expose exporter metrics port
    depends_on:
      - linux-kafka
    networks:
      - linux-kafka-net

networks:
  linux-kafka-net:
    driver: bridge
